name: Prepare environment
description: Prepare some commonly used variables.

inputs:
  event_name:
    description: The GitHub event name
    default: ${{ github.event_name }}
    required: false

  ref_type:
    description: The GitHub ref type
    default: ${{ github.event.ref_type }}
    required: false

  ref:
    description: The GitHub ref
    default: ${{ github.event.ref }}
    required: false

outputs:
  branch_name:
    description: The name of the current branch.

  escaped_branch_name:
    description: An escaped version of `branch_name` that can be safely used to construct deployment names.

branding:
  icon: "gift"
  color: "blue"

runs:
  using: "node12"
  main: "dist/main.js"
